#include <fstream>
#include <string>
#include <iostream>

int main(){
    std::fstream f("input.txt");
    std::string line {};
    int x = 1, new_cycle = 0, value = 0, total = 0, cycletocheck = 20; 
    int cycles[] = {1, 2};

    char screen[6][40];

    /* inputs generated by AOC will always run for 40 * 6 cycles because that's how many pixels the screen has  */
    /* you might need to change this for example input */
    for(int cycle = 0; cycle < 40 * 6; cycle++) {
        std::string cmd {};
        if(cycle == cycletocheck){
            cycletocheck += 40;
            total += (x * cycle);
        }

        if(new_cycle == cycle){
            x += value;
            f >> cmd;
            if(cmd == "noop"){
                new_cycle = cycle + cycles[0];
                value = 0;
            } else {
                f >> value;
                new_cycle = cycle + cycles[1];
            }
        }

        int pixelno = cycle % 40;
        if(pixelno == (x - 1) || pixelno == x || pixelno == (x + 1)){
            screen[cycle / 40][pixelno] = '#'; 
        } else {
            screen[cycle / 40][pixelno] = '.'; 
        }
    }

    std::cout << "Total: " << total << std::endl;

    for(int i = 0; i < 6; i++){
        for(int j = 0; j < 40; j++){
            std::cout << screen[i][j] << " ";
        }
        std::cout << std::endl;
    }
    return 0;
}